import Head from 'next/head'

// components
import FAQ from '../components/Layout/FAQ'
import Features from '../components/Layout/Features'
import HeaderNetflix from '../components/Layout/HeaderNetflix'


export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix looks like</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <HeaderNetflix />
      <Features />
      <FAQ />
    </>
  )
}
