// next
import Head from 'next/head'

// components
import Header from '../components/Layout/Header'


export default function Home() {
  return (
    <>
      <Head>
        <title>Netflix looks like</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Header />
    </>
  )
}
